### ISSUE TITLE
@angular/router: 3.4.8 breaks initial redirect

### ISSUE THREAD

**Issue by Chuvisco88** [Greentube/localize-router#30] opened 2017-02-20 14:33 UTC
Before upgrading the router from 3.4.7 to 3.4.8 the following happened:
`localhost:3000 => localhost:3000/de/karten/standard`

After the upgrade I receive the following redirect:
`localhost:3000 => localhost:3000/cards/standard`

Obviously a bugfix in the angular router broke the translated redirects.
I upgraded all my dependencies manually and step by step and the problem occurred as soon as I upgraded the angular dependencies.

Will try to look into that as well

**Comment by meeroslav** [comment] 2017-02-20 14:37
Hi @Chuvisco88, this is duplicate of #25

**Closed** 2017-02-20 14:38 UTC
Labels: duplicate
