### ISSUE TITLE
One module without routing

### ISSUE THREAD

**Issue by sggonzalezg** [Greentube/localize-router#51] opened 2017-05-17 15:56 UTC
How can I use one module without the routing?

I want to do localhost/module 
not localhost/es/module or localhost/en/module

It's possible? @meeroslav

**Comment by meeroslav** [comment] 2017-05-24 11:34
Currently it's not. However since you are already the second person requesting this ([https://github.com/Greentube/localize-router/issues/48](https://github.com/Greentube/localize-router/issues/48)) I will look into into it.

I will close this as it's duplicate of above mentioned issue.

**Closed by meeroslav** 2017-05-24 11:34 UTC
