### ISSUE TITLE
"Cannot match any routes" after page refresh

### ISSUE THREAD

**Issue by mrzepinski** [Greentube/localize-router#25] opened 2017-02-15 09:01 UTC
I got "Cannot match any routes" after page refresh in my appliaction.
Without `localize-router` everything work fine.

With: `LocalizeRouterModule.forRoot(appRoutes)` in my `app.module.ts` I got an error in the browser.

"@angular/cli": "1.0.0-beta.31"
"@angular/compiler-cli": ">=4.0.0-beta <5.0.0"
"@angular/common": ">=4.0.0-beta <5.0.0"
"@angular/compiler": ">=4.0.0-beta <5.0.0"
"@angular/core": ">=4.0.0-beta <5.0.0"
"@angular/http": ">=4.0.0-beta <5.0.0"
"@angular/platform-browser": ">=4.0.0-beta <5.0.0"
"@angular/platform-browser-dynamic": ">=4.0.0-beta <5.0.0"
"@angular/router": ">=4.0.0-beta <5.0.0"
"ng2-translate": "5.0.0"
"localize-router": "0.6.2"

**Comment by meeroslav** [comment] 2017-02-15 09:17
Can you provide more information:
- what route are you loading?
- how does your appRoutes look like?
- if possible provide link to your repo

Thanks

**Comment by mrzepinski** [comment] 2017-02-15 09:20
@meeroslav It's part of enterprise project, so it's not available online.

My `appRoutes` is simple:

```
export const appRoutes: Routes = [
  {
    path: '',
    component: DashboardComponent
  },
  {
    path: 'admin',
    children: [
      {
        path: 'active-sessions',
        component: AdminActiveSessionsComponent
      }
    ]
  }
];
```

1. Load homepage
2. Go to `admin/active-sessions`
3. Refresh the page (F5)
4. Error

**Comment by meeroslav** [comment] 2017-02-15 09:24
Well,  `admin/active-sessions ` should be invalid.
Once localize-router kicks in, proper URL should be e.g. `en/admin/active-sessions` so the message you get is correct.
Do you navigate through the application to the given route or you modify the browser URL manually?
Former would be a bug in `localize-router` while later would be expected behavior.

Please note that there is possibility to add flag to exclude certain routes from the localization process, but it's not yet implemented.

**Comment by mrzepinski** [comment] 2017-02-15 09:27
@meeroslav Sure, it's `en/admin/active-sessions`. I skipped this for clarity.
I navigate through the application. I just refresh the page by pressing F5.

**Comment by meeroslav** [comment] 2017-02-15 12:26
@mrzepinski This would notmaly happen if you would be using lazy loaded routes (#3). If this is not the case, then I will investigate it as soon as possible.

**Comment by mrzepinski** [comment] 2017-02-15 12:28
@meeroslav It's not this case. I'm not using lazy loaded routes.

**Comment by Chuvisco88** [comment] 2017-02-20 13:34
@mrzepinski Could you provide the navigation link as well?

**Comment by meeroslav** [comment] 2017-02-20 14:36
This is caused by router version 3.4.8. Seems that navigation kicks in before APP_INITIALIZER finishes.

**Comment by Chuvisco88** [comment] 2017-02-20 14:49
Yeah, looked into the changes (https://github.com/angular/angular/compare/2.4.7...2.4.8).
Looks like the process changed. They added a `LOCATION_INITIALIZED` which might help

**Comment by meeroslav** [comment] 2017-02-20 15:02
This will break the backwards compatibility unfortunately, not to mention 4.x.x versions.
I need to investigate more to find proper solution.

**Comment by meeroslav** [comment] 2017-02-21 13:17
Issue mentioned in [https://github.com/angular/angular/issues/14615](https://github.com/angular/angular/issues/14615)

**Comment by meeroslav** [comment] 2017-02-22 21:57
Workaround for version 2.4.8. can be found here: [https://github.com/angular/angular/issues/14588](https://github.com/angular/angular/issues/14588).

Proper solution will be done soon.

**Comment by CamusAran** [comment] 2017-03-04 23:02
Any update on this?

**Comment by meeroslav** [comment] 2017-03-07 13:10
Resolved with Angular version 2.4.9

**Closed by meeroslav** 2017-03-07 13:10 UTC
Labels: bug

**Comment by CamusAran** [comment] 2017-03-08 22:29
Nice.

Any plans to support the new process that is used in Angular 4? There will apparently be a legacy option that makes it work like in 2.x but you can't use that with Universal.

**Comment by GoshaFighten** [comment] 2017-03-10 12:41
@meeroslav 
When are we going to have a new version supporting Angular 2.4.9?

**Comment by meeroslav** [comment] 2017-03-13 14:19
The new version should be there in few days, I'm working on tests.

In the meantime, if you don't mind npm complaining, version 0.6.4 is fully functional with **Angular Core** 2.4.9 (and **Angular Router** 3.4.9).

**Comment by CamusAran** [comment] 2017-03-25 22:50
@meeroslav 
What about Angular 4.0.0 support?

**Comment by meeroslav** [comment] 2017-04-07 16:37
On it. Sorry for waiting.

**Comment by meeroslav** [comment] 2017-04-18 13:26
Version 0.7.0 supports Angular 4

**Comment by headonkeyboard** [comment] 2017-07-03 07:39
I'm also having an issue like this on the new version of localize-router with a lazy module but steps to reproduce are quite different.

App routes : 

```
const routes: Routes = [
  {
    path: 'user',
    loadChildren: 'app/auth/auth.module#AuthModule'
  }
];
```
Auth routes :

```
const routes: Routes = [
  {
    path: '',
    component: AuthComponent,
  },
  {
    path : 'login',
    component: LoginComponent,
  },
  {
    path: 'subscription',
    component: SubscriptionComponent
  }
];
```
- When I enter "http://localhost:4200/en/user/subscription" or "http://localhost:4200/en/user/" directly in browser, there is no problem, components are correctly lazy loaded.

- With "http://localhost:4200/fr/utilisateur" it works great

- But with "http://localhost:4200/fr/utilisateur/inscription" I've got this error `Cannot match any routes. URL Segment: 'fr/utilisateur/inscription'`

I have another problem with this configuration when I put my links directly in the "app.component.html" file. 
- This works : `<a [routerLink]="'/user' | localize">{{ 'Login' | translate }}</a>`
- This needs two clicks on link : `<a [routerLink]="'/user/subscription' | localize">{{ 'Subscription' | translate }}</a>` (First click throw this error `Cannot match any routes. URL Segment: 'fr/utilisateur/inscription'` and second click works)
