### ISSUE TITLE
Lazzy loading through loadChildren not working for child routes.

### ISSUE THREAD

**Issue by Rj-s** [Greentube/localize-router#18] opened 2017-01-10 18:27 UTC
Issue:- 
**Routing is not happening in lazy loaded modules through loadChildren route configuration.** 

environment:- 
angular-cli: 1.0.0-beta.24
node: 6.4.0
os: win32 x64
@angular/router: 3.4.2
@angular/compiler-cli: 2.4.2
localize-router: ^0.4.0,
ng2-translate: ^4.0.0,

main app routing:- 
export const routes: Routes = [
  { path: '', redirectTo: 'login', pathMatch: 'full' },
  { path: 'login', component: LoginComponent }
  { path: 'web', loadChildren: 'app/modules/web/web.module#WebModule' }
];

web routing in WebModule:-
export const routes: Routes = [
  {  path: 'web', component: WebComponent, children: [
  { path: 'home', component: HomeComponent }
    ]
  }
]; 

Observed:-
1. When try to redirect to '/web'. WebModule file gets fetched from server in network and url changed to 'en/web'  but  blank page gets displayed with no error in console.
2. When try to redirect to '/web/home' :-  Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'en/web/home'

Expected:- There should not be any error in console and child module should get fetched lazily with working child routes in url.

**Comment by meeroslav** [comment] 2017-01-11 13:57
This is duplicate of #3

**Closed by meeroslav** 2017-01-11 13:57 UTC
