### ISSUE TITLE
Not working with Angular 5.2.7

### ISSUE THREAD

**Issue by azzimuth** [Greentube/localize-router#115] opened 2018-03-02 10:37 UTC
I was perfectly working with Angular 5.2.1 but it stopped working once Angular 5.2.7 became available. Any ideas when a new compatible package will be released?

**Comment by Yomyer** [comment] 2018-03-05 11:51
It works well until version 5.2.6 :'(

**Comment by gizbo** [comment] 2018-03-05 15:32
Confirmed. not working with 5.2.7. Any idea what's going on?

**Comment by yarikshlyakhov** [comment] 2018-03-10 21:50
there are any estimation when this issue will be fixed?

**Comment by chintan13** [comment] 2018-03-14 16:30
yes it seems there is some update in 5.2.7 for router 

router: don't mutate route configs (#22358) (8f0a064), closes #22203

I am not getting what is changed, if any one can help me I'd love to contribute for it

**Comment by cbetrifork** [comment] 2018-03-15 09:19
It seems that only when using changeLanguage() and then using any route, it breaks.

And it is only the "@angular/router", that can't be upgraded to "5.2.7", downgrading to "5.2.6" works for now.

For a minimal testing repo, use your own demo project "cli", it breaks the same way.

**Comment by Hezard** [comment] 2018-03-22 23:35
Hi all!
I found an issue, its new immutable function in angular router
https://github.com/angular/angular/pull/22358
they changed this method
```
resetConfig(config: Routes): void {
   validateConfig(config);
   this.config = config.map(copyConfig);
   this.navigated = false;
}
```

After that, we can't use shared object (this.parser.routes) between angular router and localize router.
Also I found few other broken things after this change:
1) Method translateRoutes of localize router has inner Observable with async data which can't resolve correctly without a direct object of routes from router
2) The second issue when you put the wrong url, even with router v5.2.6 you I will get an error about parsing segmentGroup
I managed second issue with this code:
```
export class RoutingModule {
  constructor(private router: Router, private localize: LocalizeRouterService) {
    this.router.errorHandler = (error) => {
        const route: any = this.localize.translateRoute(['/404']);
        this.router.navigate(route); // or redirect to default route
    }
  }
 }
```

Here is possible fix for router localize, I think we need to update these methods
LocalizeRouterService.changeLanguage:
```
this.router.resetConfig(this.parser.routes);
if (useNavigateMethod) {
    this.router.navigate([url], extras);
} else {
    this.router.navigateByUrl(url, extras);
}
```
LocalizeRouterService._routeChanged:
```
if (currentLang !== previousLang) {
    this.parser.translateRoutes(currentLang).
    do(this.router.resetConfig(this.parser.routes)).
    subscribe(() => {
        // Fire route change event
        this.router.resetConfig(this.parser.routes);
        this.routerEvents.next(currentLang);
    });
}
```

LocalizeParser.translateRoutes:
```
translateRoutes(language: string): Observable<any> {
    this._cachedLang = language;
    if (this._languageRoute) {
      this._languageRoute.path = language;
    }

    return this.translate.use(language).
      map((translations: any) => {
        this._translationObject = translations;
        this.currentLang = language;

        if (this._languageRoute) {
          if (this._languageRoute) {
            this._translateRouteTree(this._languageRoute.children);
          }
          // if there is wildcard route
          if (this._wildcardRoute && this._wildcardRoute.redirectTo) {
            this._translateProperty(this._wildcardRoute, 'redirectTo', true);
          }
        } else {
          this._translateRouteTree(this.routes);
        }

      });
}
```

**Comment by gilsdav** [comment] 2018-04-15 14:24
I created a fix but I probably didn't test all cases : https://github.com/gilsdav/localize-router/tree/new_router

**Comment by manzonif** [comment] 2018-05-15 15:05
@Hezard in LocalizeRouterService.changeLanguage, we have:

`changeLanguage(lang: string, extras?: NavigationExtras, useNavigateMethod?: boolean): void {
    if (lang !== this.parser.currentLang) {
      let rootSnapshot: ActivatedRouteSnapshot = this.router.routerState.snapshot.root;

      this.parser.translateRoutes(lang).subscribe(() => {
        let url = this.traverseRouteSnapshot(rootSnapshot);`

After translateRoutes is processed, the rootSnapshot should be translated, so that traverseRouteSnapshot, should return the correct translated url.

I think this does not happen because of the new immutable function.

**Comment by meeroslav** [comment] 2018-11-04 21:20
@pzhuk, @azzimuth, since this happens only on versions 5.2.7-5.2.10 I've decided not to fix it as it would complicate versioning.

That being said, it is fixed for version 2.x.x which require Angular 6 or 7. This version is still in alpha so expect final version in the upcoming days.

**Closed by meeroslav** 2018-11-04 21:20 UTC
