### ISSUE TITLE
no language in path doesn't use default

### ISSUE THREAD

**Issue by Masquer** [Greentube/localize-router#20] opened 2017-02-05 21:07 UTC
Here's the quote from README:
> If no language is provided in the url path, application uses default path - language set in the browser or first locale in the config. Make sure you therefore place most common language (e.g. 'en') as a first string in the array of locales.

But I don't notice the behavior described; the [demo app](https://github.com/meeroslav/localize-router-example) also acts the other way.

Steps to reproduce in demo app:
- navigate somewhere (i.e.) to '/en/users' -- it works
- type in path without language, as '/users' -- it doesn't work

Desired behavior -- '/users' auto redirects to '/en/users' as first and default language, please any tips to meet that?

**Comment by meeroslav** [comment] 2017-02-06 09:06
Hi @Masquer, it might be that documentation is a bit misleading. Thanks for pointing that out. Documentation only explains the algorithm by which language gets chosen.

Localize-router prepends all the routes with selected language and creates a redirect to base language url e.g. `my/route/path` will become `en/my/route/path`. Once localize-router had been initialized it overrides the initial routes, so route `my/route/path` no longer exists in RouterConfig and Router therefore returns 404. This is not defect, it's by design as above mentioned route is invalid.

There are two approaches to solve your request:
- By catching 404 and redirecting to {localize.parser.currentLang}/{location.path} manually in project
- By handling this in localize-router

Please note that at the moment this has low prio against lazy loading, and most likely will not be implemented any time soon.

**Comment by brunorentcars** [comment] 2017-02-06 18:10
how can I add exception in router?

**Comment by meeroslav** [comment] 2017-02-06 19:03
@brunorentcars If you refer to catching 404 you can do it by pointing all unknown routes (**) to the component that will handle the redirection.

[https://angular.io/docs/ts/latest/guide/router.html](https://angular.io/docs/ts/latest/guide/router.html)

If this is not what you're referring to, then please provide more information.

**Comment by brunorentcars** [comment] 2017-02-06 19:13
if I set a different language on URI there isn't on configuration file(locales.json) my application crashes.

There routers for 404:
{path: '404', component: NotFoundComponent},
{path: '**', redirectTo: '404'}


But localize-router put this routers inside children language route.
For example:
{path: '', redirectTo: 'en', pathMatch: 'full'}
{path: 'en', children: [
    {path: '404', component: NotFoundComponent},
    {path: '**', redirectTo: '404'}
]}

**Comment by meeroslav** [comment] 2017-02-07 15:45
@brunorentcars please create a separate issue for this and I'll get on to it asap. Thanks!

**Comment by juanmcampos** [comment] 2017-02-20 18:25
hello @brunorentcars just wondering if you managed to accomplish this behavior? Thnx

**Comment by brunorentcars** [comment] 2017-02-20 18:33
@juanmcampos check this issue: https://github.com/Greentube/localize-router/issues/22

**Comment by juanmcampos** [comment] 2017-02-20 19:45
@brunorentcars great! thnx I updated my module version, and was able to get that '**' wilcard route. But any clue on how do I get the requested url? so i can handle the translate? any help would be awesome really thnx

**Comment by brunorentcars** [comment] 2017-02-21 11:37
@juanmcampos if you want to get the current route path, you can use ActivatedRoute.
For example:
`
constructor(private activatedRoute:ActivatedRoute) {
    console.log(this.activatedRoute.snapshot.url)
}
`
If you want to get the full uri, you can use Router.
For example:
`
constructor(private router:Router) {
    console.log(this.router.url)
}
`

**Comment by dahfazz** [comment] 2017-02-22 16:44
Hi @meeroslav

I'm dealing with a similar issue; On load everything is OK.
I'm on    ***/en/home

There, I click on a link on which i put [routerLink]=['users' | localize]

It throws an error because /users doesn't exist anymore, and I should target /en/users

I thought it was exactly why I need to use localize Pipe.

What am I missing please ?

**Comment by meeroslav** [comment] 2017-02-22 18:44
Short answer - you need to prefix base routes with backslash 

```ts
['/users' | localize]
```

I will provide more details once I reach my computer, in case you are interested.

**Comment by meeroslav** [comment] 2017-04-12 15:05
Closing as this will not be implemented.

**Closed by meeroslav** 2017-04-12 15:05 UTC
Labels: enhancement, help wanted, Low priority
